services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    container_name: userservice.api
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    networks:
      - delivery-net
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - userservice.database
    env_file:
      - .env

  userservice.grpc:
    image: ${DOCKER_REGISTRY-}userservicegrpc
    container_name: userservice.grpc
    build:
      context: .
      dockerfile: UserService.Grpc/Dockerfile
    networks:
      - delivery-net
    ports:
      - 5100:5100
      - 5101:5101
    depends_on:
      - userservice.database
    env_file:
      - .env

  userservice.database:
    image: postgres:latest
    container_name: userservice.database
    networks:
      - delivery-net
    ports:
      - 5401:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  delivery-net:
    external: true
