services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    networks:
      - delivery-net
    ports:
      - 5000:5001
      - 5001:5001
    depends_on:
      - userservice.database
    env_file:
      - .env
    volumes:
      - bills:/app/SharedBills

  userservice.grpc:
    image: ${DOCKER_REGISTRY-}userservicegrpc
    build:
      context: .
      dockerfile: UserService.Grpc/Dockerfile
    networks:
      - delivery-net
    ports:
      - 5100:5100
      - 5101:5101
    depends_on:
      - userservice.database
    env_file:
      - .env

  userservice.database:
    image: postgres:latest
    container_name: userservice.database
    networks:
      - delivery-net
    ports:
      - 5401:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - delivery-net

volumes:
  pgdata:
  bills:

networks:
  delivery-net:
    external: true