version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - delivery-net
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5600:5000"
      - "5644:5644"
    networks:
      - delivery-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - delivery-net
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  delivery-net:
    external: true

volumes:
  esdata: