services:
  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: ..
      dockerfile: APIGateway/Ocelot/OcelotGateway/Dockerfile
    networks:
      - delivery-net
    ports:
      - 7000:7000
      - 7001:7001
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - delivery-net
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:

networks:
  delivery-net:
    external: true
